#include "Components.h"

REFLECT_BEGIN(CPlayerControl)
REFLECT_MEMBER(thrust)
REFLECT_MEMBER(rotateSpeed)
REFLECT_MEMBER(dampening)
REFLECT_END()

REFLECT_BEGIN(CDrawable)
REFLECT_MEMBER(lineThickness)
REFLECT_END()

REFLECT_BEGIN(CText)
REFLECT_MEMBER(text)
REFLECT_MEMBER(visible)
REFLECT_END()

REFLECT_BEGIN(CTransform)
REFLECT_MEMBER(pos)
REFLECT_MEMBER(rot)
REFLECT_MEMBER(sca)
REFLECT_MEMBER(vel)
REFLECT_END()

REFLECT_BEGIN(CBullet)
REFLECT_MEMBER(speed)
REFLECT_END()

REFLECT_BEGIN(CAsteroid)
REFLECT_MEMBER(hitCount)
REFLECT_END()

REFLECT_BEGIN(CCollidable)
REFLECT_MEMBER(radius)
REFLECT_END()

REFLECT_BEGIN(CInvincibility)
REFLECT_MEMBER(m_timer)
REFLECT_MEMBER(m_flashTimer)
REFLECT_END()