#include "Components.h"

REFLECT_BEGIN(CPlayerControl)
REFLECT_MEMBER(thrust)
REFLECT_MEMBER(rotateSpeed)
REFLECT_MEMBER(dampening)
REFLECT_END()

REFLECT_BEGIN(CBullet)
REFLECT_MEMBER(speed)
REFLECT_END()

REFLECT_BEGIN(CAsteroid)
REFLECT_MEMBER(hitCount)
REFLECT_END()

REFLECT_BEGIN(CCollidable)
REFLECT_MEMBER(radius)
REFLECT_END()

REFLECT_BEGIN(CInvincibility)
REFLECT_MEMBER(m_timer)
REFLECT_MEMBER(m_flashTimer)
REFLECT_END()