#include "Components.h"

REFLECT_BEGIN(CPlayerControl)
REFLECT_MEMBER(m_thrust)
REFLECT_MEMBER(m_rotateSpeed)
REFLECT_MEMBER(m_dampening)
REFLECT_END()

REFLECT_BEGIN(CDrawable)
REFLECT_MEMBER(m_lineThickness)
REFLECT_END()

REFLECT_BEGIN(CText)
REFLECT_MEMBER(m_text)
REFLECT_MEMBER(m_visible)
REFLECT_END()

REFLECT_BEGIN(CTransform)
REFLECT_MEMBER(m_pos)
REFLECT_MEMBER(m_rot)
REFLECT_MEMBER(m_sca)
REFLECT_MEMBER(m_vel)
REFLECT_END()

REFLECT_BEGIN(CBullet)
REFLECT_MEMBER(m_speed)
REFLECT_END()

REFLECT_BEGIN(CAsteroid)
REFLECT_MEMBER(m_hitCount)
REFLECT_END()

REFLECT_BEGIN(CCollidable)
REFLECT_MEMBER(m_radius)
REFLECT_END()
