#include "Transform.h"

REFLECT_TEMPLATED_BEGIN(Transformf)
REFLECT_MEMBER(trans)
REFLECT_MEMBER(rot)
REFLECT_MEMBER(sca)
REFLECT_END()

REFLECT_TEMPLATED_BEGIN(Transformd)
REFLECT_MEMBER(trans)
REFLECT_MEMBER(rot)
REFLECT_MEMBER(sca)
REFLECT_END()

