#include "Vec3.h"

REFLECT_TEMPLATED_BEGIN(Vec3f)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_MEMBER(z)
REFLECT_END()

REFLECT_TEMPLATED_BEGIN(Vec3d)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_MEMBER(z)
REFLECT_END()