#include "Quat.h"

REFLECT_TEMPLATED_BEGIN(Quatf)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_MEMBER(z)
REFLECT_MEMBER(w)
REFLECT_END()

REFLECT_TEMPLATED_BEGIN(Quatd)
REFLECT_MEMBER(x)
REFLECT_MEMBER(y)
REFLECT_MEMBER(z)
REFLECT_MEMBER(w)
REFLECT_END()

